// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: engine_to_bts.proto

package engine_to_bts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId     uint32 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Amount    uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	RequestId int64  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_to_bts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_to_bts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_engine_to_bts_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type Triple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
	B int64 `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	C int64 `protobuf:"varint,4,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *Triple) Reset() {
	*x = Triple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_to_bts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Triple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triple) ProtoMessage() {}

func (x *Triple) ProtoReflect() protoreflect.Message {
	mi := &file_engine_to_bts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triple.ProtoReflect.Descriptor instead.
func (*Triple) Descriptor() ([]byte, []int) {
	return file_engine_to_bts_proto_rawDescGZIP(), []int{1}
}

func (x *Triple) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Triple) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Triple) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

type GetTriplesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Triples []*Triple `protobuf:"bytes,1,rep,name=triples,proto3" json:"triples,omitempty"`
}

func (x *GetTriplesResponse) Reset() {
	*x = GetTriplesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_to_bts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTriplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTriplesResponse) ProtoMessage() {}

func (x *GetTriplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_to_bts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTriplesResponse.ProtoReflect.Descriptor instead.
func (*GetTriplesResponse) Descriptor() ([]byte, []int) {
	return file_engine_to_bts_proto_rawDescGZIP(), []int{2}
}

func (x *GetTriplesResponse) GetTriples() []*Triple {
	if x != nil {
		return x.Triples
	}
	return nil
}

type GetRandBitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Randbits []int64 `protobuf:"varint,1,rep,packed,name=randbits,proto3" json:"randbits,omitempty"`
}

func (x *GetRandBitsResponse) Reset() {
	*x = GetRandBitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_to_bts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandBitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandBitsResponse) ProtoMessage() {}

func (x *GetRandBitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_to_bts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandBitsResponse.ProtoReflect.Descriptor instead.
func (*GetRandBitsResponse) Descriptor() ([]byte, []int) {
	return file_engine_to_bts_proto_rawDescGZIP(), []int{3}
}

func (x *GetRandBitsResponse) GetRandbits() []int64 {
	if x != nil {
		return x.Randbits
	}
	return nil
}

var File_engine_to_bts_proto protoreflect.FileDescriptor

var file_engine_to_bts_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x62, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x74, 0x6f, 0x62,
	0x74, 0x73, 0x22, 0x60, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x4a, 0x04,
	0x08, 0x03, 0x10, 0x04, 0x22, 0x32, 0x0a, 0x06, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x63, 0x22, 0x43, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d,
	0x0a, 0x07, 0x74, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x74, 0x6f, 0x62, 0x74, 0x73, 0x2e, 0x54, 0x72,
	0x69, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x74, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x31, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x64, 0x62, 0x69, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x64, 0x62, 0x69, 0x74, 0x73,
	0x32, 0xa3, 0x01, 0x0a, 0x0b, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x54, 0x6f, 0x42, 0x74, 0x73,
	0x12, 0x48, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x17,
	0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x74, 0x6f, 0x62, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x74, 0x6f, 0x62, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x69, 0x70, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x69, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x74, 0x6f, 0x62, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x74, 0x6f, 0x62, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2d, 0x64, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x2f, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x4d, 0x50, 0x43, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x62,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engine_to_bts_proto_rawDescOnce sync.Once
	file_engine_to_bts_proto_rawDescData = file_engine_to_bts_proto_rawDesc
)

func file_engine_to_bts_proto_rawDescGZIP() []byte {
	file_engine_to_bts_proto_rawDescOnce.Do(func() {
		file_engine_to_bts_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_to_bts_proto_rawDescData)
	})
	return file_engine_to_bts_proto_rawDescData
}

var file_engine_to_bts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_engine_to_bts_proto_goTypes = []interface{}{
	(*GetRequest)(nil),          // 0: enginetobts.GetRequest
	(*Triple)(nil),              // 1: enginetobts.Triple
	(*GetTriplesResponse)(nil),  // 2: enginetobts.GetTriplesResponse
	(*GetRandBitsResponse)(nil), // 3: enginetobts.GetRandBitsResponse
}
var file_engine_to_bts_proto_depIdxs = []int32{
	1, // 0: enginetobts.GetTriplesResponse.triples:type_name -> enginetobts.Triple
	0, // 1: enginetobts.EngineToBts.GetTriples:input_type -> enginetobts.GetRequest
	0, // 2: enginetobts.EngineToBts.GetRandBits:input_type -> enginetobts.GetRequest
	2, // 3: enginetobts.EngineToBts.GetTriples:output_type -> enginetobts.GetTriplesResponse
	3, // 4: enginetobts.EngineToBts.GetRandBits:output_type -> enginetobts.GetRandBitsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engine_to_bts_proto_init() }
func file_engine_to_bts_proto_init() {
	if File_engine_to_bts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_to_bts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_to_bts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Triple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_to_bts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTriplesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_to_bts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandBitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_to_bts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_to_bts_proto_goTypes,
		DependencyIndexes: file_engine_to_bts_proto_depIdxs,
		MessageInfos:      file_engine_to_bts_proto_msgTypes,
	}.Build()
	File_engine_to_bts_proto = out.File
	file_engine_to_bts_proto_rawDesc = nil
	file_engine_to_bts_proto_goTypes = nil
	file_engine_to_bts_proto_depIdxs = nil
}
