cc_library(
    name = "math",
    srcs = [
        "Math.cpp"
    ],
    hdrs = [
        "Math.hpp",
    ],
    deps = [
        "//Share:share",
        "//LogHeader:logger",
        "//Logging:log",
    ],
    visibility = ["//visibility:public"],
)
