cc_library(
    name = "computation",
    srcs = [
        "Computation.cpp"
    ],
    hdrs = [
        "Computation.hpp",
    ],
    deps = [
        "//Math:math",
        "@nlohmann_json//:json",
        "//LogHeader:logger"
    ],
    visibility = ["//visibility:public"],
)
