version: "3.3"
services:
  cc:
    container_name: computation_container1
    tty: true # 起動しっぱなし
    build:
      context: ../../../
      dockerfile: packages/server/ComputationContainer/Dockerfile
      target: src
    expose:
      - "50120"
      - "51120"
      - "50110"
    volumes:
      - type: bind
        source: .
        target: /QuickMPC
      # bazelのビルド成果物を永続化
      - type: bind
        source: ./.cache
        target: /root/.cache
      - type: bind
        source: ../../../proto
        target: /proto
      - type: bind
        source: ../../../Config/ComputationContainer/Compute1
        target: /QuickMPC/Config
      # srcステージ用の.src.envを.envに上書きする(テスト時にファイルを直接読み込むため)
      - type: bind
        source: ../../../Config/ComputationContainer/Compute1/.src.env
        target: /QuickMPC/Config/.env
      # 開発環境のフォーマッタを統一
      - type: bind
        source: ../../../.vscode
        target: /QuickMPC/.vscode
      - type: bind
        source: ../.clang-format
        target: /QuickMPC/.clang-format
      - type: bind
        source: ../Db/
        target: /Db
    env_file:
      - ../../../Config/ComputationContainer/Compute1/.src.env
      - ../../../Config/ComputationContainer/JWT/client.sample.env
    networks:
      shared-network:
        ipv4_address: 10.0.1.120

networks:
  shared-network:
    external: true
