version: "3.3"
services:
  mc:
    container_name: manage_container1
    tty: true # 起動しっぱなし
    expose:
      - "50110"
      - "50111"
    build:
      context: ../../../
      dockerfile: packages/server/manage_container/Dockerfile
      target: src
    volumes:
      - type: bind
        source: .
        target: /QuickMPC
      - type: bind
        source: ../../../proto
        target: /proto
      - type: bind
        source: ../../../config/manage_container/manage1
        target: /QuickMPC/config
      # 開発環境のフォーマッタを統一
      - type: bind
        source: ../../../.vscode
        target: /QuickMPC/.vscode
      - type: bind
        source: ../db/
        target: /db
    env_file:
      - ../../../config/manage_container/manage1/.src.env
    networks:
      shared-network:
        ipv4_address: 10.0.1.110

  envoy:
    container_name: manage_envoy_container1
    tty: true # 起動しっぱなし
    image: envoyproxy/envoy:v1.17.1
    volumes:
      - type: bind
        source: ./envoy.yaml
        target: /etc/envoy/envoy.yaml
    ports:
      - "9001:9001"
    command: ["/bin/sh", "-c", "/usr/local/bin/envoy -c /etc/envoy/envoy.yaml"]
networks:
  shared-network:
    external: true
