runs:
  using: "composite"
  steps:
    # Setup config for using GCS as bazel remote cache
    - name: Update GCP service account JSON
      run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/computation_container/sa.json
      shell: bash
      env:
        CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

    - name: Update .bazelrc for using remote cache
      run: |
        eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
      shell: bash
      env:
        BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      shell: bash