cc_library(
    name = "math_lib",
    srcs = [
        "MathLib.cpp"
    ],
    hdrs = [
        "MathLib.hpp",
    ],
    visibility = ["//visibility:public"]
)

cc_library(
    name = "fixed_point",
    hdrs = [
        "FixedPoint.hpp",
    ],
    visibility = ["//visibility:public"]
)
