apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp:
  labels:
    io.kompose.service: resultdb
  name: resultdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
