apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp:
  labels:
    io.kompose.service: sharedb
  name: sharedb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
