cc_library(
    name = "config_parse",
    hdrs = [
        "ConfigParse.hpp",
    ],
    deps = [
        "@nlohmann_json//:json",
        "//LogHeader:logger",
        "//Logging:log",
    ],
    visibility = ["//visibility:public"],
)