cc_library(
    name = "helper",
    hdrs = [
        "Helper.hpp"
    ],
    deps = [
        "//LogHeader:logger",
        "@Proto//ComputationToComputationContainer:computation_to_computation_cc_grpc",
    ],
    visibility = ["//visibility:public"],
)