cc_library(
    name = "triple_handler",
    hdrs = [
        "TripleHandler.hpp",
    ],
    deps = [
        "//PrimeField:prime_field",
        "//FixedPoint:fixed_point",
        "//Share:address",
        "//Client/ComputationToBts:client",
    ],
    visibility = ["//visibility:public"],
)