version: '3.3'
services:
  datadog:
    container_name: datadog
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    environment:
      - DD_SITE=us5.datadoghq.com
      - DD_API_KEY=${DD_API_KEY}
      - DD_TAGS=env:${USER}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE="name:datadog"
    ports:
      - 0.0.0.0:8126:8126