# require {docker-compose.core.yml}
version: '3.3'
services:
  dev_bts:
    container_name: beaver_triple_service
    image: tags_dev_bts
    build:
      context: ../
      dockerfile: packages/server/beaver_triple_service/Dockerfile
      target: dev
    command:
      - /bin/bash
      - '-c'
      - ./beaver_triple_service
    env_file:
      - ../config/beaver_triple_service/.env
      - ../config/beaver_triple_service/client.sample.env
      - ../config/beaver_triple_service/server.sample.env
    healthcheck:
      test:
        - CMD-SHELL
        - /bin/grpc_health_probe -addr=beaver_triple_service:50020 -rpc-header=authorization:"bearer $$BTS_TOKEN"
      interval: 3s
      start_period: 5s
      timeout: 5s
    ports:
      - 0.0.0.0:60020:50020
  dev_bts_envoy:
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - target: /etc/envoy/envoy.yaml
        source: ../config/beaver_triple_service/envoy.yaml
        type: bind
    command:
      - /bin/sh
      - '-c'
      - /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    expose:
      - 9901
    ports:
      - 0.0.0.0:51020:51020
    tty: true
  dev_cc_envoy1:
    container_name: compute_envoy_container1
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - target: /etc/envoy/envoy.yaml
        source: ../config/computation_container/compute1/envoy.yaml
        type: bind
    command:
      - /bin/sh
      - '-c'
      - /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    expose:
      - 50020
      - 51020
    tty: true
  dev_cc_envoy2:
    container_name: compute_envoy_container2
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - target: /etc/envoy/envoy.yaml
        source: ../config/computation_container/compute2/envoy.yaml
        type: bind
    command:
      - /bin/sh
      - '-c'
      - /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    expose:
      - 50020
      - 51020
    tty: true
  dev_cc_envoy3:
    container_name: compute_envoy_container3
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - target: /etc/envoy/envoy.yaml
        source: ../config/computation_container/compute3/envoy.yaml
        type: bind
    command:
      - /bin/sh
      - '-c'
      - /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    expose:
      - 50020
      - 51020
    tty: true
  dev_cc1:
    container_name: computation_container1
    image: tags_dev_cc
    build:
      context: ../
      dockerfile: packages/server/computation_container/Dockerfile
      target: dev
    volumes:
      - target: /QuickMPC/config
        source: ../config/computation_container/compute1
        type: bind
      - target: /db/share
        source: sharedb1
        type: volume
      - target: /db/result
        source: resultdb1
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./computation_container
    env_file:
      - ../config/computation_container/compute1/.env
    healthcheck:
      test:
        - CMD-SHELL
        - /bin/grpc_health_probe -addr=computation_container1:50010 && /bin/grpc_health_probe -addr=computation_container1:51020
      interval: 3s
      start_period: 5s
      timeout: 5s
    expose:
      - 51020
      - 50010
    tty: true
  dev_cc2:
    container_name: computation_container2
    image: tags_dev_cc
    build:
      context: ../
      dockerfile: packages/server/computation_container/Dockerfile
      target: dev
    volumes:
      - target: /QuickMPC/config
        source: ../config/computation_container/compute2
        type: bind
      - target: /db/share
        source: sharedb2
        type: volume
      - target: /db/result
        source: resultdb2
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./computation_container
    env_file:
      - ../config/computation_container/compute2/.env
    healthcheck:
      test:
        - CMD-SHELL
        - /bin/grpc_health_probe -addr=computation_container2:50010 && /bin/grpc_health_probe -addr=computation_container2:51020
      interval: 3s
      start_period: 5s
      timeout: 5s
    expose:
      - 51020
      - 50010
    tty: true
  dev_cc3:
    container_name: computation_container3
    image: tags_dev_cc
    build:
      context: ../
      dockerfile: packages/server/computation_container/Dockerfile
      target: dev
    volumes:
      - target: /QuickMPC/config
        source: ../config/computation_container/compute3
        type: bind
      - target: /db/share
        source: sharedb3
        type: volume
      - target: /db/result
        source: resultdb3
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./computation_container
    env_file:
      - ../config/computation_container/compute3/.env
    healthcheck:
      test:
        - CMD-SHELL
        - /bin/grpc_health_probe -addr=computation_container3:50010 && /bin/grpc_health_probe -addr=computation_container3:51020
      interval: 3s
      start_period: 5s
      timeout: 5s
    expose:
      - 51020
      - 50010
    tty: true
  dev_mc_envoy1:
    container_name: manage_envoy_container1
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - target: /etc/envoy/envoy.yaml
        source: ../config/manage_container/manage1/envoy.yaml
        type: bind
    command:
      - /bin/sh
      - '-c'
      - /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    expose:
      - 15000
      - 50010
    ports:
      - 0.0.0.0:50001:50000
    tty: true
  dev_mc_envoy2:
    container_name: manage_envoy_container2
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - target: /etc/envoy/envoy.yaml
        source: ../config/manage_container/manage2/envoy.yaml
        type: bind
    command:
      - /bin/sh
      - '-c'
      - /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    expose:
      - 15000
      - 50010
    ports:
      - 0.0.0.0:50002:50000
    tty: true
  dev_mc_envoy3:
    container_name: manage_envoy_container3
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - target: /etc/envoy/envoy.yaml
        source: ../config/manage_container/manage3/envoy.yaml
        type: bind
    command:
      - /bin/sh
      - '-c'
      - /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    expose:
      - 15000
      - 50010
    ports:
      - 0.0.0.0:50003:50000
    tty: true
  dev_mc1:
    container_name: manage_container1
    image: tags_dev_mc
    build:
      context: ../
      dockerfile: packages/server/manage_container/Dockerfile
      target: dev
    volumes:
      - target: /QuickMPC/config
        source: ../config/manage_container/manage1
        type: bind
      - target: /QuickMPC/.vscode
        source: ../.vscode
        type: bind
      - target: /db/share
        source: sharedb1
        type: volume
      - target: /db/result
        source: resultdb1
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./manage_container
    env_file:
      - ../config/manage_container/manage1/.env
    healthcheck:
      test:
        - CMD-SHELL
        - /bin/grpc_health_probe -addr=manage_container1:50011 && /bin/grpc_health_probe -addr=manage_container1:51011
      interval: 3s
      start_period: 5s
      timeout: 5s
    expose:
      - 50011
      - 51011
    tty: true
  dev_mc2:
    container_name: manage_container2
    image: tags_dev_mc
    build:
      context: ../
      dockerfile: packages/server/manage_container/Dockerfile
      target: dev
    volumes:
      - target: /QuickMPC/config
        source: ../config/manage_container/manage2
        type: bind
      - target: /db/share
        source: sharedb2
        type: volume
      - target: /db/result
        source: resultdb2
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./manage_container
    env_file:
      - ../config/manage_container/manage2/.env
    healthcheck:
      test:
        - CMD-SHELL
        - /bin/grpc_health_probe -addr=manage_container2:50011 && /bin/grpc_health_probe -addr=manage_container2:51011
      interval: 3s
      start_period: 5s
      timeout: 5s
    expose:
      - 50011
      - 51011
    tty: true
  dev_mc3:
    container_name: manage_container3
    image: tags_dev_mc
    build:
      context: ../
      dockerfile: packages/server/manage_container/Dockerfile
      target: dev
    volumes:
      - target: /QuickMPC/config
        source: ../config/manage_container/manage3
        type: bind
      - target: /db/share
        source: sharedb3
        type: volume
      - target: /db/result
        source: resultdb3
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./manage_container
    env_file:
      - ../config/manage_container/manage3/.env
    healthcheck:
      test:
        - CMD-SHELL
        - /bin/grpc_health_probe -addr=manage_container3:50011 && /bin/grpc_health_probe -addr=manage_container3:51011
      interval: 3s
      start_period: 5s
      timeout: 5s
    expose:
      - 50011
      - 51011
    tty: true
