# require {docker-compose.core.yml, docker-compose.dev.yml}
version: '3.3'
services:
  medium_cc1:
    container_name: computation_container1
    depends_on:
      dev_bts:
        condition: service_healthy
      dev_cc_envoy1:
        condition: service_started
    image: tags_medium_cc
    build:
      context: ../
      dockerfile: packages/server/computation_container/Dockerfile
      target: medium
    volumes:
      - target: /QuickMPC/config
        source: ../config/computation_container/compute1
        type: bind
      - target: /db/share
        source: sharedb1
        type: volume
      - target: /db/result
        source: resultdb1
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./computation_container_test
    env_file:
      - ../config/computation_container/compute1/.env
    expose:
      - 51020
      - 50010
  medium_cc2:
    container_name: computation_container2
    depends_on:
      dev_bts:
        condition: service_healthy
      dev_cc_envoy2:
        condition: service_started
    image: tags_medium_cc
    build:
      context: ../
      dockerfile: packages/server/computation_container/Dockerfile
      target: medium
    volumes:
      - target: /QuickMPC/config
        source: ../config/computation_container/compute2
        type: bind
      - target: /db/share
        source: sharedb2
        type: volume
      - target: /db/result
        source: resultdb2
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./computation_container_test
    env_file:
      - ../config/computation_container/compute2/.env
    expose:
      - 51020
      - 50010
  medium_cc3:
    container_name: computation_container3
    depends_on:
      dev_bts:
        condition: service_healthy
      dev_cc_envoy3:
        condition: service_started
    image: tags_medium_cc
    build:
      context: ../
      dockerfile: packages/server/computation_container/Dockerfile
      target: medium
    volumes:
      - target: /QuickMPC/config
        source: ../config/computation_container/compute3
        type: bind
      - target: /db/share
        source: sharedb3
        type: volume
      - target: /db/result
        source: resultdb3
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && ./computation_container_test
    env_file:
      - ../config/computation_container/compute3/.env
    expose:
      - 51020
      - 50010
    tty: true
  medium_mc1:
    container_name: manage_container1
    depends_on:
      dev_mc_envoy1:
        condition: service_started
    image: tags_medium_mc
    build:
      context: ../
      dockerfile: packages/server/manage_container/Dockerfile
      target: medium
    volumes:
      - target: /QuickMPC/config
        source: ../config/manage_container/manage1
        type: bind
      - target: /db/share
        source: sharedb1
        type: volume
      - target: /db/result
        source: resultdb1
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && go test ./integration_test/... -v -cover
    env_file:
      - ../config/manage_container/manage1/.env
    expose:
      - 50011
      - 51011
  medium_mc2:
    container_name: manage_container2
    depends_on:
      dev_mc_envoy2:
        condition: service_started
    image: tags_medium_mc
    build:
      context: ../
      dockerfile: packages/server/manage_container/Dockerfile
      target: medium
    volumes:
      - target: /QuickMPC/config
        source: ../config/manage_container/manage2
        type: bind
      - target: /db/share
        source: sharedb2
        type: volume
      - target: /db/result
        source: resultdb2
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && go test ./integration_test/... -v -cover
    env_file:
      - ../config/manage_container/manage2/.env
    expose:
      - 50011
      - 51011
  medium_mc3:
    container_name: manage_container3
    depends_on:
      dev_mc_envoy3:
        condition: service_started
    image: tags_medium_mc
    build:
      context: ../
      dockerfile: packages/server/manage_container/Dockerfile
      target: medium
    volumes:
      - target: /QuickMPC/config
        source: ../config/manage_container/manage3
        type: bind
      - target: /db/share
        source: sharedb3
        type: volume
      - target: /db/result
        source: resultdb3
        type: volume
    command:
      - /bin/bash
      - '-c'
      - printenv && go test ./integration_test/... -v -cover
    env_file:
      - ../config/manage_container/manage3/.env
    expose:
      - 50011
      - 51011
  medium-libc:
    container_name: libclient
    depends_on:
      dev_mc1:
        condition: service_healthy
      dev_mc_envoy1:
        condition: service_started
      dev_mc2:
        condition: service_healthy
      dev_mc_envoy2:
        condition: service_started
      dev_mc3:
        condition: service_healthy
      dev_mc_envoy3:
        condition: service_started
      dev_cc1:
        condition: service_healthy
      dev_cc_envoy1:
        condition: service_started
      dev_cc2:
        condition: service_healthy
      dev_cc_envoy2:
        condition: service_started
      dev_cc3:
        condition: service_healthy
      dev_cc_envoy3:
        condition: service_started
      dev_bts:
        condition: service_healthy
    image: tags_medium_libc
    build:
      context: ../
      dockerfile: scripts/libclient/Dockerfile
      target: medium
    volumes:
      - target: /libclient/data
        source: ./libclient/data
        type: bind
      - target: /libclient/src
        source: ./libclient/src
        type: bind
    command:
      - /bin/bash
      - '-c'
      - pip list && pytest src/tests -s -v -log-cli-level=DEBUG --durations=0
    network_mode: host
