version: '3.3'
services:
  datadog:
    container_name: datadog
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    env_file:
      - ./datadog/.env
    ports:
      - 0.0.0.0:8126:8126