version: "3.3"
services:
  bts:
    container_name: beaver_triple_service
    tty: true # 起動しっぱなし
    build:
      context: ../../../
      dockerfile: packages/server/beaver_triple_service/Dockerfile
      target: src
    volumes:
      - type: bind
        source: .
        target: /QuickMPC
      - type: bind
        source: ../../../config/beaver_triple_service
        target: /QuickMPC/config
      - type: bind
        source: ../../../proto
        target: /proto
    env_file:
      - ../../../config/beaver_triple_service/.env
      - ../../../config/beaver_triple_service/client.sample.env
      - ../../../config/beaver_triple_service/server.sample.env
    ports:
      - "127.0.0.1:64101:54100"
    # command: ["/bin/bash", "-c", "go mod vendor && go build && ./beaver_triple_service"]
    # healthcheck:
    #   test: ["CMD-SHELL", "/bin/grpc_health_probe -addr=beaver_triple_service:54100"]
    #   interval: 3s
    #   timeout: 5s
    #   start_period: 5s
