AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  # use host zone "qmpc.run"
  HostedZoneName:
    Description: domain name
    Default: "qmpc.run"
    Type: String
  ExistingAwsVpc:
    Description: Name of existing AWS Vpc
    Type: AWS::EC2::VPC::Id
  ExistingEIP:
    Description: EIP
    Type: String
  ExistingLoadbalancer:
    Description: ARN of existing Application Loadbalancer
    Type: String
  ExistingLoadbalancerDNSName:
    Description: The Demo App Loadbalancer DNSName
    Type: String
  ExistingLoadbalancerZoneId:
    Description: The Demo App Loadbalancer CanonicalHostedZoneID
    Type: String
  HostedZoneId:
    Type: String
    Default: "Z01453211ISUMGHFXVZVK"
    Description: Host Zone Id
  RecordName:
    Type: String
    Description: Record Name

Resources:
  # レコードの作成
  route53RSGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Sub "${HostedZoneId}"
      # Create Record
      RecordSets:
        - Name: !Sub "${RecordName}.${HostedZoneName}"
          AliasTarget:
            HostedZoneId: !Sub "${ExistingLoadbalancerZoneId}"
            DNSName: !Sub "${ExistingLoadbalancerDNSName}"
          Type: A

  # ACM
  ACM:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "${RecordName}.${HostedZoneName}"
      DomainValidationOptions:
        - DomainName: !Sub "${RecordName}.${HostedZoneName}"
          HostedZoneId: !Sub "${HostedZoneId}"
      SubjectAlternativeNames:
        - !Sub "*.${RecordName}.${HostedZoneName}"
      ValidationMethod: DNS

  # ALG target group
  ALBTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Sub "${ExistingAwsVpc}"

  # ALB https listener
  ALBListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ACM
      DefaultActions:
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward
      LoadBalancerArn: !Sub "${ExistingLoadbalancer}"

Outputs:
  CertId:
    Description: The ID of the certificate for TLS communication
    Value: !Ref 'ACM'
