runs:
  using: "composite"
  steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      shell: bash
      run: |
        pip install -U pip
        pip install pytest
        pip install ./packages/client/libclient-py

    - name: Set up Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build bts with cache
      uses: ./.github/actions/build_images_with_cache
      with:
        container-name: "dev_bts"
        cache-key: ${{ hashFiles('./packages/server/beaver_triple_service/**') }}
        dockerfile-path: ./packages/server/beaver_triple_service/Dockerfile
        builder-name: ${{ steps.buildx.outputs.name }}
        target: "dev"

    - name: Build cc with cache
      uses: ./.github/actions/build_images_with_cache
      with:
        container-name: "dev_cc"
        cache-key: ${{ hashFiles('./packages/server/computation_container/**') }}
        dockerfile-path: ./packages/server/computation_container/Dockerfile
        builder-name: ${{ steps.buildx.outputs.name }}
        target: "dev"

    - name: Build mc with cache
      uses: ./.github/actions/build_images_with_cache
      with:
        container-name: "dev_mc"
        cache-key: ${{ hashFiles('./packages/server/manage_container/**') }}
        dockerfile-path: ./packages/server/manage_container/Dockerfile
        builder-name: ${{ steps.buildx.outputs.name }}
        target: "dev"
