##### Protobuf Rules for Bazel
##### See https://github.com/bazelbuild/rules_proto
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

##### gtest
http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    sha256 = "b58cb7547a28b2c718d1e38aee18a3659c9e3ff52440297e965f5edffe34b6d0",
    build_file = "@//:Gtest.BUILD",
    strip_prefix = "googletest-release-1.7.0",
)

# Enable Proto
local_repository(
    name = "Proto",
    path = "/Proto"
)

load("@Proto//bazel:repositories.bzl", "Proto_repositories")
Proto_repositories()
load("@Proto//bazel:Proto_deps.bzl", "Proto_deps")
Proto_deps()
load("@Proto//bazel:Proto_extra_deps.bzl", "Proto_extra_deps")
Proto_extra_deps()

# Enable libsodium
new_local_repository(
    name = "libsodium",
    path = "/usr/local/lib",
    build_file = "@//:sodium.BUILD"
)

# Enable libOTe
new_local_repository(
    name = "libOTe",
    path = "/usr/local/lib",
    build_file = "@//:OTe.BUILD"
)

# Enable nlohman/json
http_archive(
    name = "nlohmann_json",
    sha256 = "6bea5877b1541d353bd77bdfbdb2696333ae5ed8f9e8cc22df657192218cad91",
    urls = [
        "https://github.com/nlohmann/json/releases/download/v3.9.1/include.zip",
    ],
    build_file = "@//ThirdParty/nlohmann_json:nlohmann_json.BUILD",
)

# Eigen
new_local_repository(
    name = "eigen",
    path = "/usr/include/eigen3",
    build_file = "@//:eigen.BUILD",
)

# spdlog
new_local_repository(
    name = "libspdlog",
    path = "/usr/local/lib",
    build_file = "@//:spdlog.BUILD"
)

# Enable bazel-compdb
http_archive(
    name = "com_grail_bazel_compdb",
    sha256 = "d32835b26dd35aad8fd0ba0d712265df6565a3ad860d39e4c01ad41059ea7eda",
    urls = ["https://github.com/grailbio/bazel-compilation-database/archive/0.5.2.tar.gz"],
    strip_prefix = "bazel-compilation-database-0.5.2",
)

load("@com_grail_bazel_compdb//:deps.bzl", "bazel_compdb_deps")
bazel_compdb_deps()
