// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: libc_to_manage.proto

package LibcToManageContainer

import (
	common_types "github.com/acompany-develop/QuickMPC/src/Proto/common_types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// the message of SendSharesRequest
type SendSharesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataId  string   `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Shares  string   `protobuf:"bytes,2,opt,name=shares,proto3" json:"shares,omitempty"`
	Schema  []string `protobuf:"bytes,3,rep,name=schema,proto3" json:"schema,omitempty"`
	PieceId int32    `protobuf:"varint,4,opt,name=piece_id,json=pieceId,proto3" json:"piece_id,omitempty"`
	SentAt  string   `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Token   string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SendSharesRequest) Reset() {
	*x = SendSharesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSharesRequest) ProtoMessage() {}

func (x *SendSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSharesRequest.ProtoReflect.Descriptor instead.
func (*SendSharesRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{0}
}

func (x *SendSharesRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *SendSharesRequest) GetShares() string {
	if x != nil {
		return x.Shares
	}
	return ""
}

func (x *SendSharesRequest) GetSchema() []string {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *SendSharesRequest) GetPieceId() int32 {
	if x != nil {
		return x.PieceId
	}
	return 0
}

func (x *SendSharesRequest) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *SendSharesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//*
// the message of SendSharesResponse
type SendSharesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOk    bool   `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *SendSharesResponse) Reset() {
	*x = SendSharesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSharesResponse) ProtoMessage() {}

func (x *SendSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSharesResponse.ProtoReflect.Descriptor instead.
func (*SendSharesResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{1}
}

func (x *SendSharesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendSharesResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

//*
// the message of DeleteSharesRequest
type DeleteSharesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataIds []string `protobuf:"bytes,1,rep,name=dataIds,proto3" json:"dataIds,omitempty"`
	Token   string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *DeleteSharesRequest) Reset() {
	*x = DeleteSharesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSharesRequest) ProtoMessage() {}

func (x *DeleteSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSharesRequest.ProtoReflect.Descriptor instead.
func (*DeleteSharesRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSharesRequest) GetDataIds() []string {
	if x != nil {
		return x.DataIds
	}
	return nil
}

func (x *DeleteSharesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//*
// the message of DeleteSharesResponse
type DeleteSharesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOk    bool   `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *DeleteSharesResponse) Reset() {
	*x = DeleteSharesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSharesResponse) ProtoMessage() {}

func (x *DeleteSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSharesResponse.ProtoReflect.Descriptor instead.
func (*DeleteSharesResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSharesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteSharesResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

//*
// the message of GetSchemaRequest
type GetSchemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataId string `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchemaRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *GetSchemaRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//*
// the message of GetSchemaResponse
type GetSchemaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOk    bool     `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	Schema  []string `protobuf:"bytes,3,rep,name=schema,proto3" json:"schema,omitempty"`
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{5}
}

func (x *GetSchemaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSchemaResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *GetSchemaResponse) GetSchema() []string {
	if x != nil {
		return x.Schema
	}
	return nil
}

//*
// the message of ExecuteComputationRequest
type JoinOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataIds []string `protobuf:"bytes,1,rep,name=dataIds,proto3" json:"dataIds,omitempty"`
	Join    []int32  `protobuf:"varint,2,rep,packed,name=join,proto3" json:"join,omitempty"`
	Index   []int32  `protobuf:"varint,3,rep,packed,name=index,proto3" json:"index,omitempty"`
}

func (x *JoinOrder) Reset() {
	*x = JoinOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinOrder) ProtoMessage() {}

func (x *JoinOrder) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinOrder.ProtoReflect.Descriptor instead.
func (*JoinOrder) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{6}
}

func (x *JoinOrder) GetDataIds() []string {
	if x != nil {
		return x.DataIds
	}
	return nil
}

func (x *JoinOrder) GetJoin() []int32 {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *JoinOrder) GetIndex() []int32 {
	if x != nil {
		return x.Index
	}
	return nil
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src    []int32 `protobuf:"varint,1,rep,packed,name=src,proto3" json:"src,omitempty"`
	Target []int32 `protobuf:"varint,2,rep,packed,name=target,proto3" json:"target,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{7}
}

func (x *Input) GetSrc() []int32 {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *Input) GetTarget() []int32 {
	if x != nil {
		return x.Target
	}
	return nil
}

type ExecuteComputationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodId common_types.ComputationMethod `protobuf:"varint,1,opt,name=method_id,json=methodId,proto3,enum=pb_common_types.ComputationMethod" json:"method_id,omitempty"`
	Token    string                         `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Table    *JoinOrder                     `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Arg      *Input                         `protobuf:"bytes,4,opt,name=arg,proto3" json:"arg,omitempty"`
}

func (x *ExecuteComputationRequest) Reset() {
	*x = ExecuteComputationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteComputationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteComputationRequest) ProtoMessage() {}

func (x *ExecuteComputationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteComputationRequest.ProtoReflect.Descriptor instead.
func (*ExecuteComputationRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteComputationRequest) GetMethodId() common_types.ComputationMethod {
	if x != nil {
		return x.MethodId
	}
	return common_types.ComputationMethod_COMPUTATION_METHOD_UNSPECIFIED
}

func (x *ExecuteComputationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExecuteComputationRequest) GetTable() *JoinOrder {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *ExecuteComputationRequest) GetArg() *Input {
	if x != nil {
		return x.Arg
	}
	return nil
}

//*
// the message of ExecuteComputationResponse
type ExecuteComputationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOk    bool   `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	JobUuid string `protobuf:"bytes,3,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
}

func (x *ExecuteComputationResponse) Reset() {
	*x = ExecuteComputationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteComputationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteComputationResponse) ProtoMessage() {}

func (x *ExecuteComputationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteComputationResponse.ProtoReflect.Descriptor instead.
func (*ExecuteComputationResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteComputationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteComputationResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *ExecuteComputationResponse) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

//*
// the message of GetComputationResultRequest
type GetComputationResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobUuid string `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetComputationResultRequest) Reset() {
	*x = GetComputationResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComputationResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComputationResultRequest) ProtoMessage() {}

func (x *GetComputationResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComputationResultRequest.ProtoReflect.Descriptor instead.
func (*GetComputationResultRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{10}
}

func (x *GetComputationResultRequest) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

func (x *GetComputationResultRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//*
// the message of GetComputationResultResponse
type GetComputationResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOk    bool                   `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	Result  string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Status  common_types.JobStatus `protobuf:"varint,4,opt,name=status,proto3,enum=pb_common_types.JobStatus" json:"status,omitempty"`
	PieceId int32                  `protobuf:"varint,5,opt,name=piece_id,json=pieceId,proto3" json:"piece_id,omitempty"`
}

func (x *GetComputationResultResponse) Reset() {
	*x = GetComputationResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComputationResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComputationResultResponse) ProtoMessage() {}

func (x *GetComputationResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComputationResultResponse.ProtoReflect.Descriptor instead.
func (*GetComputationResultResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{11}
}

func (x *GetComputationResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetComputationResultResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *GetComputationResultResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetComputationResultResponse) GetStatus() common_types.JobStatus {
	if x != nil {
		return x.Status
	}
	return common_types.JobStatus_UNKNOWN
}

func (x *GetComputationResultResponse) GetPieceId() int32 {
	if x != nil {
		return x.PieceId
	}
	return 0
}

//*
// the message of SendModelParamRequest
type SendModelParamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobUuid string `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	Params  string `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	PieceId int32  `protobuf:"varint,3,opt,name=piece_id,json=pieceId,proto3" json:"piece_id,omitempty"`
	Token   string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SendModelParamRequest) Reset() {
	*x = SendModelParamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendModelParamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendModelParamRequest) ProtoMessage() {}

func (x *SendModelParamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendModelParamRequest.ProtoReflect.Descriptor instead.
func (*SendModelParamRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{12}
}

func (x *SendModelParamRequest) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

func (x *SendModelParamRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *SendModelParamRequest) GetPieceId() int32 {
	if x != nil {
		return x.PieceId
	}
	return 0
}

func (x *SendModelParamRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//*
// the message of SendModelParamResponse
type SendModelParamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOk    bool   `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *SendModelParamResponse) Reset() {
	*x = SendModelParamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendModelParamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendModelParamResponse) ProtoMessage() {}

func (x *SendModelParamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendModelParamResponse.ProtoReflect.Descriptor instead.
func (*SendModelParamResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{13}
}

func (x *SendModelParamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendModelParamResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

//*
// the message of PredictRequest
type PredictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobUuid           string                     `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	ModelParamJobUuid string                     `protobuf:"bytes,2,opt,name=model_param_job_uuid,json=modelParamJobUuid,proto3" json:"model_param_job_uuid,omitempty"`
	ModelId           common_types.PredictMethod `protobuf:"varint,3,opt,name=model_id,json=modelId,proto3,enum=pb_common_types.PredictMethod" json:"model_id,omitempty"`
	Table             *JoinOrder                 `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Src               []int32                    `protobuf:"varint,5,rep,packed,name=src,proto3" json:"src,omitempty"`
	Token             string                     `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{14}
}

func (x *PredictRequest) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

func (x *PredictRequest) GetModelParamJobUuid() string {
	if x != nil {
		return x.ModelParamJobUuid
	}
	return ""
}

func (x *PredictRequest) GetModelId() common_types.PredictMethod {
	if x != nil {
		return x.ModelId
	}
	return common_types.PredictMethod_PREDICT_METHOD_UNSPECIFIED
}

func (x *PredictRequest) GetTable() *JoinOrder {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *PredictRequest) GetSrc() []int32 {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *PredictRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//*
// the message of PredictResponse
type PredictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOk    bool   `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{15}
}

func (x *PredictResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PredictResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type GetDataListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetDataListRequest) Reset() {
	*x = GetDataListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataListRequest) ProtoMessage() {}

func (x *GetDataListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataListRequest.ProtoReflect.Descriptor instead.
func (*GetDataListRequest) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{16}
}

func (x *GetDataListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetDataListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	IsOk   bool   `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *GetDataListResponse) Reset() {
	*x = GetDataListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libc_to_manage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataListResponse) ProtoMessage() {}

func (x *GetDataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libc_to_manage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataListResponse.ProtoReflect.Descriptor instead.
func (*GetDataListResponse) Descriptor() ([]byte, []int) {
	return file_libc_to_manage_proto_rawDescGZIP(), []int{17}
}

func (x *GetDataListResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetDataListResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

var File_libc_to_manage_proto protoreflect.FileDescriptor

var file_libc_to_manage_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x69, 0x62, 0x63, 0x5f, 0x74, 0x6f, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x1a, 0x1f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x61,
	0x74, 0x61, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69, 0x65, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x69, 0x65, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x43,
	0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13,
	0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69,
	0x73, 0x4f, 0x6b, 0x22, 0x45, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61,
	0x74, 0x61, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x74,
	0x61, 0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x45, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x0a, 0x05,
	0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f,
	0x6b, 0x22, 0x41, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x22, 0x4f, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x31, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72,
	0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x22, 0xc8, 0x01, 0x0a, 0x19, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3f, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74,
	0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x61, 0x72, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x03, 0x61, 0x72, 0x67, 0x22,
	0x66, 0x0a, 0x1a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x19, 0x0a, 0x08,
	0x6a, 0x6f, 0x62, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6a, 0x6f, 0x62, 0x55, 0x75, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xb4, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69, 0x65, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x69, 0x65, 0x63, 0x65, 0x49, 0x64, 0x22, 0x7b,
	0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69,
	0x65, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x69,
	0x65, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x16, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x69, 0x73, 0x4f, 0x6b, 0x22, 0xee, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x2f, 0x0a, 0x14, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x5f, 0x6a, 0x6f, 0x62, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4a, 0x6f, 0x62, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x2d,
	0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x72, 0x63, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x40, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x22, 0x2a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x42, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x32, 0xe7, 0x05, 0x0a, 0x0c, 0x4c, 0x69, 0x62, 0x63,
	0x54, 0x6f, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x6c, 0x69,
	0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x12, 0x1e, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x6c, 0x69, 0x62,
	0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x71, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x5d, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x23, 0x2e, 0x6c, 0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6c, 0x69, 0x62, 0x63,
	0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x12, 0x1c, 0x2e, 0x6c,
	0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x69, 0x62,
	0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x6c, 0x69, 0x62,
	0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6c,
	0x69, 0x62, 0x63, 0x74, 0x6f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2d, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x2f, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x4d, 0x50, 0x43, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x4c, 0x69, 0x62, 0x63, 0x54, 0x6f, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_libc_to_manage_proto_rawDescOnce sync.Once
	file_libc_to_manage_proto_rawDescData = file_libc_to_manage_proto_rawDesc
)

func file_libc_to_manage_proto_rawDescGZIP() []byte {
	file_libc_to_manage_proto_rawDescOnce.Do(func() {
		file_libc_to_manage_proto_rawDescData = protoimpl.X.CompressGZIP(file_libc_to_manage_proto_rawDescData)
	})
	return file_libc_to_manage_proto_rawDescData
}

var file_libc_to_manage_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_libc_to_manage_proto_goTypes = []interface{}{
	(*SendSharesRequest)(nil),            // 0: libctomanage.SendSharesRequest
	(*SendSharesResponse)(nil),           // 1: libctomanage.SendSharesResponse
	(*DeleteSharesRequest)(nil),          // 2: libctomanage.DeleteSharesRequest
	(*DeleteSharesResponse)(nil),         // 3: libctomanage.DeleteSharesResponse
	(*GetSchemaRequest)(nil),             // 4: libctomanage.GetSchemaRequest
	(*GetSchemaResponse)(nil),            // 5: libctomanage.GetSchemaResponse
	(*JoinOrder)(nil),                    // 6: libctomanage.JoinOrder
	(*Input)(nil),                        // 7: libctomanage.Input
	(*ExecuteComputationRequest)(nil),    // 8: libctomanage.ExecuteComputationRequest
	(*ExecuteComputationResponse)(nil),   // 9: libctomanage.ExecuteComputationResponse
	(*GetComputationResultRequest)(nil),  // 10: libctomanage.GetComputationResultRequest
	(*GetComputationResultResponse)(nil), // 11: libctomanage.GetComputationResultResponse
	(*SendModelParamRequest)(nil),        // 12: libctomanage.SendModelParamRequest
	(*SendModelParamResponse)(nil),       // 13: libctomanage.SendModelParamResponse
	(*PredictRequest)(nil),               // 14: libctomanage.PredictRequest
	(*PredictResponse)(nil),              // 15: libctomanage.PredictResponse
	(*GetDataListRequest)(nil),           // 16: libctomanage.GetDataListRequest
	(*GetDataListResponse)(nil),          // 17: libctomanage.GetDataListResponse
	(common_types.ComputationMethod)(0),  // 18: pb_common_types.ComputationMethod
	(common_types.JobStatus)(0),          // 19: pb_common_types.JobStatus
	(common_types.PredictMethod)(0),      // 20: pb_common_types.PredictMethod
}
var file_libc_to_manage_proto_depIdxs = []int32{
	18, // 0: libctomanage.ExecuteComputationRequest.method_id:type_name -> pb_common_types.ComputationMethod
	6,  // 1: libctomanage.ExecuteComputationRequest.table:type_name -> libctomanage.JoinOrder
	7,  // 2: libctomanage.ExecuteComputationRequest.arg:type_name -> libctomanage.Input
	19, // 3: libctomanage.GetComputationResultResponse.status:type_name -> pb_common_types.JobStatus
	20, // 4: libctomanage.PredictRequest.model_id:type_name -> pb_common_types.PredictMethod
	6,  // 5: libctomanage.PredictRequest.table:type_name -> libctomanage.JoinOrder
	0,  // 6: libctomanage.LibcToManage.SendShares:input_type -> libctomanage.SendSharesRequest
	2,  // 7: libctomanage.LibcToManage.DeleteShares:input_type -> libctomanage.DeleteSharesRequest
	4,  // 8: libctomanage.LibcToManage.GetSchema:input_type -> libctomanage.GetSchemaRequest
	8,  // 9: libctomanage.LibcToManage.ExecuteComputation:input_type -> libctomanage.ExecuteComputationRequest
	10, // 10: libctomanage.LibcToManage.GetComputationResult:input_type -> libctomanage.GetComputationResultRequest
	12, // 11: libctomanage.LibcToManage.SendModelParam:input_type -> libctomanage.SendModelParamRequest
	14, // 12: libctomanage.LibcToManage.Predict:input_type -> libctomanage.PredictRequest
	16, // 13: libctomanage.LibcToManage.GetDataList:input_type -> libctomanage.GetDataListRequest
	1,  // 14: libctomanage.LibcToManage.SendShares:output_type -> libctomanage.SendSharesResponse
	3,  // 15: libctomanage.LibcToManage.DeleteShares:output_type -> libctomanage.DeleteSharesResponse
	5,  // 16: libctomanage.LibcToManage.GetSchema:output_type -> libctomanage.GetSchemaResponse
	9,  // 17: libctomanage.LibcToManage.ExecuteComputation:output_type -> libctomanage.ExecuteComputationResponse
	11, // 18: libctomanage.LibcToManage.GetComputationResult:output_type -> libctomanage.GetComputationResultResponse
	13, // 19: libctomanage.LibcToManage.SendModelParam:output_type -> libctomanage.SendModelParamResponse
	15, // 20: libctomanage.LibcToManage.Predict:output_type -> libctomanage.PredictResponse
	17, // 21: libctomanage.LibcToManage.GetDataList:output_type -> libctomanage.GetDataListResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_libc_to_manage_proto_init() }
func file_libc_to_manage_proto_init() {
	if File_libc_to_manage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_libc_to_manage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSharesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSharesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSharesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSharesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSchemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSchemaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteComputationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteComputationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComputationResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComputationResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendModelParamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendModelParamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libc_to_manage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libc_to_manage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libc_to_manage_proto_goTypes,
		DependencyIndexes: file_libc_to_manage_proto_depIdxs,
		MessageInfos:      file_libc_to_manage_proto_msgTypes,
	}.Build()
	File_libc_to_manage_proto = out.File
	file_libc_to_manage_proto_rawDesc = nil
	file_libc_to_manage_proto_goTypes = nil
	file_libc_to_manage_proto_depIdxs = nil
}
