name: QuickMPC Benchmark


on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

jobs:
  benchmark-test:
    name: Benchmark test
    runs-on: ubuntu-latest
    # releaseタグがtriggerの時のみ走らせる
    # if: ${{ !startsWith(github.event.workflow_run.head_branch, 'main') }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "TAG_NAME=$latest_tag" >> $GITHUB_ENV

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - name: setup
        run: ./setup.sh ${{ env.TAG_NAME }} ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} ${{ secrets.GCP_PROJECT_ID }}
        working-directory: ./benchmark_src/

      - name: create gcp instance
        run: terraform init && terraform plan && terraform apply --auto-approve && terraform output -json > ../application/output.json
        working-directory: ./demo/terraform/gcp

      - name: deploy quickmpc
        run: terraform init && terraform plan && terraform apply --auto-approve && terraform output -json > ../../../benchmark_src/terraform/output.json
        working-directory: ./demo/terraform/application

      - name: benchmark test
        run: terraform init && terraform plan && terraform apply --auto-approve
        working-directory: ./benchmark_src/terraform

      - if: always()
        name: post-processing
        run: terraform destroy --auto-approve
        working-directory: ./demo/terraform/gcp
