name: LargeTest for CC, MC, DB

env:
  CC_IMAGE_NAME: cc_test
  MC_IMAGE_NAME: mc_test
  DBG_IMAGE_NAME: dbg_test
  SHARE_DB_IMAGE_NAME: sharedb_test
  # Largeテストを行うサーバをAzureで立てている
  LARGE_ENDPOINT1: https://ec2-3-18-248-215.us-east-2.compute.amazonaws.com:3001

on:
  pull_request:
    branches: [check]

jobs:
  # LargeテストのためCCのイメージをpush
  build_and_push_cc:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build CC image
        run: docker build ../../ --file Dockerfile --target large-runner --tag ghcr.io/${{ github.repository_owner }}/${{ env.CC_IMAGE_NAME }}:${{ github.run_id }}
        working-directory: ./src/ComputationContainer/

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.CC_IMAGE_NAME }}:${{ github.run_id }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [build_and_push_cc]

    steps:
      - name: Merge All build_and_push
        run: echo "ok"

  # CCのLargeテストを実行
  large_test:
    runs-on: ubuntu-latest
    # build_and_pushが通らないと実行しない
    needs: build_and_push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger Larget Test and Wait for the Result
        run: ./wait_for_large.sh ${{ secrets.CI_AUTH_TOKEN }} ${{ env.LARGE_ENDPOINT1 }} ${{ github.event.pull_request.number }} "${{ github.event.pull_request.title }}" ${{ github.event.pull_request.html_url }} ${{ github.run_id }} # 結果を取得するまで待つ
        working-directory: ./Test/Large/
        timeout-minutes: 120
