name: Build CC, MC, DB and Run Build and Test in Each Containers

on:
  pull_request:
    branches:
      - main
      - "feature/**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format tool
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt-get update
          sudo apt-get install clang-format-14
      - name: Check if *.{cpp|hpp} files are formatted
        run: |
          cd ${{ github.workspace }}/src/
          make check

  small_test_cc:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./src/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./src/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build images and run ComputationContainer
        run: make test t=./ComputationContainer m=build p=small
        working-directory: ./Test

      - name: Run bazel test in ComputationContainer
        run: make test t=./ComputationContainer m=run p=small
        working-directory: ./Test

  small_test_mc:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images and run ManageContainer
        run: make test t=./ManageContainer m=build p=small
        working-directory: ./Test

      - name: Run Go test in ManageContainer
        run: make test t=./ManageContainer m=run p=small
        working-directory: ./Test

  small_test_dc:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images and run secrets-server shareDbContainer DbGate
        run: make test t=./DbContainer m=build p=small
        working-directory: ./Test

      - name: Run Go test in DbContainers
        run: make test t=./DbContainer m=run p=small
        working-directory: ./Test

  small_test:
    runs-on: ubuntu-latest
    needs: [lint, small_test_cc, small_test_mc, small_test_dc]

    steps:
      - name: Merge All small_test
        run: echo "ok"

  medium_test_cc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./src/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./src/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build images and run ComputationContainer
        run: make test t=./ComputationContainer m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in ComputationContainer
        run: make test t=./ComputationContainer m=run p=medium
        working-directory: ./Test

  medium_test_mc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images and run ManageContainer
        run: make test t=./ManageContainer m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in ManageContainer
        run: make test t=./ManageContainer m=run p=medium
        working-directory: ./Test

  medium_test_dc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images and run DbContainer
        run: make test t=./DbContainer m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in DbContainer
        run: make test t=./DbContainer m=run p=medium
        working-directory: ./Test

  medium_test_libclient:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./src/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./src/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build images and run LibClient
        run: make test t=./LibClient m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in LibClient
        run: make test t=./LibClient m=run p=medium
        working-directory: ./Test

  medium_test:
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        medium_test_cc,
        medium_test_mc,
        medium_test_dc,
        medium_test_libclient,
      ]

    steps:
      - name: Merge All medium_test
        run: echo "ok"

  # 安定バージョンのQMPCイメージをpush
  build_and_push_cc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build CC image
        run: |
          docker build ../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-cc:${{ github.run_id }}
        working-directory: ./src/ComputationContainer/

      - name: Run Trivy vulnerability scanner for CC
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-cc:${{ github.run_id }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-cc:${{ github.run_id }}

  build_and_push_mc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build MC image
        run: |
          docker build ../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-mc:${{ github.run_id }}
        working-directory: ./src/ManageContainer/

      - name: Run Trivy vulnerability scanner for MC
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-mc:${{ github.run_id }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-mc:${{ github.run_id }}

  build_and_push_dc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build DbGate image
        run: |
          docker build ../../../ --file Dockerfile --target dep --build-arg lowercase_DB_NAMES=sharedb --tag ghcr.io/${{ github.repository_owner }}/quickmpc-dbg:${{ github.run_id }}
        working-directory: ./src/DbContainer/DbGate/

      - name: Run Trivy vulnerability scanner for DbGate
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-dbg:${{ github.run_id }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Build sharedb image
        run: |
          docker build ../../../ --file Dockerfile --target dep --build-arg lowercase_DB_NAME=sharedb --tag ghcr.io/${{ github.repository_owner }}/quickmpc-sharedb:${{ github.run_id }}
        working-directory: ./src/DbContainer/Db/

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-dbg:${{ github.run_id }}
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-sharedb:${{ github.run_id }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [lint, build_and_push_cc, build_and_push_mc, build_and_push_dc]

    steps:
      - name: Merge All build_and_push
        run: echo "ok"
