name: Push Stable CC, MC Image

on:
  push:
    branches:
      - main
      - "release/**"

jobs:
  # 安定バージョンのQMPCイメージをpush
  build_and_push_cc:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set current date as env variable
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build CC image
        run: |
          docker buildx build ../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-cc:s${{ steps.date.outputs.date }} --load
          docker buildx build ../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-cc:stable                          --load
        working-directory: ./src/ComputationContainer/

      - name: Run Trivy vulnerability scanner for CC
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-cc:s${{ steps.date.outputs.date }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-cc:s${{ steps.date.outputs.date }}
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-cc:stable

  build_and_push_mc:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set current date as env variable
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build MC image
        run: |
          docker buildx build ../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-mc:s${{ steps.date.outputs.date }} --load
          docker buildx build ../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-mc:stable                          --load
        working-directory: ./src/ManageContainer/

      - name: Run Trivy vulnerability scanner for MC
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-mc:s${{ steps.date.outputs.date }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-mc:s${{ steps.date.outputs.date }}
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-mc:stable

  build_and_push:
    runs-on: ubuntu-latest
    needs: [build_and_push_cc, build_and_push_mc]

    steps:
      - name: Merge All build_and_push
        run: echo "ok"
