name: Push Stable CC, MC Image

on:
  push:
    branches:
      - main
      - "release/**"
    tags:
      - "*"

jobs:
  # 安定バージョンのQMPCイメージをpush
  build_and_push_cc:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set current date as env variable
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quickmpc-cc

      - name: Build CC image by branch
        if: github.event.payload.ref_type == 'branch'
        run: |
          docker buildx build ../../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-cc:s${{ steps.date.outputs.date }} --load
          docker buildx build ../../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-cc:stable                          --load
        working-directory: ./packages/server/ComputationContainer/

      - name: Build CC image by tag
        if: github.event.payload.ref_type == 'tag'
        run: |
          docker buildx build ../../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-cc:${{ steps.meta.outputs.tags }} --load
        working-directory: ./packages/server/ComputationContainer/

      - name: Run Trivy vulnerability scanner for CC with branch
        if: github.event.payload.ref_type == 'branch'
        uses: aquasecurity/trivy-action@master
        with:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       c
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-cc:s${{ steps.date.outputs.date }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Run Trivy vulnerability scanner for CC with tag
        if: github.event.payload.ref_type == 'tag'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-cc:${{ steps.meta.outputs.tags }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image with branch
        if: github.event.payload.ref_type == 'branch'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-cc:s${{ steps.date.outputs.date }}
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-cc:stable

      - name: Push image with tag
        if: github.event.payload.ref_type == 'tag'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-cc:${{ steps.meta.outputs.tags }}

  build_and_push_mc:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set current date as env variable
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quickmpc-mc

      - name: Build MC image with branch
        if: github.event.payload.ref_type == 'branch'
        run: |
          docker buildx build ../../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-mc:s${{ steps.date.outputs.date }} --load
          docker buildx build ../../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-mc:stable                          --load
        working-directory: ./packages/server/ManageContainer/

      - name: Build MC image with tag
        if: github.event.payload.ref_type == 'tag'
        run: |
          docker buildx build ../../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-mc:${{ steps.meta.outputs.tags }} --load
        working-directory: ./packages/server/ManageContainer/

      - name: Run Trivy vulnerability scanner for MC with branch
        if: github.event.payload.ref_type == 'branch'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-mc:s${{ steps.date.outputs.date }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Run Trivy vulnerability scanner for MC with tag
        if: github.event.payload.ref_type == 'tag'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/quickmpc-mc:${{ steps.meta.outputs.tags }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image with branch
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-mc:s${{ steps.date.outputs.date }}
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-mc:stable

      - name: Push image with tag
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-mc:${{ steps.meta.outputs.tags }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [build_and_push_cc, build_and_push_mc]

    steps:
      - name: Merge All build_and_push
        run: echo "ok"
