name: Build and Run Tests on CC, MC, and BTS Containers

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format tool
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt-get update
          sudo apt-get install clang-format-14
      - name: Check if *.{cpp|hpp} files are formatted
        run: |
          cd ${{ github.workspace }}/packages/server/
          make check

  small_test_cc:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/computation_container/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-small_cc-${{ hashFiles('./packages/server/computation_container/**') }}
          restore-keys: ${{ runner.os }}-small_cc-

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/computation_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=small_cc,src=/tmp/.buildx-cache
          cache-to: type=local,scope=small_cc,dest=/tmp/.buildx-cache-new
          target: small
          tags: tags_small_cc
          load: true

      - name: Run bazel test in computation_container
        run: make test t=./computation_container m=run p=small
        working-directory: ./scripts

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  small_test_mc:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-small_mc-${{ hashFiles('./packages/server/manage_container/**') }}
          restore-keys: ${{ runner.os }}-small_mc-

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/manage_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=small_mc,src=/tmp/.buildx-cache
          cache-to: type=local,scope=small_mc,dest=/tmp/.buildx-cache-new
          target: small
          tags: tags_small_mc
          load: true

      - name: Run Go test in manage_container
        run: make test t=./manage_container m=run p=small
        working-directory: ./scripts

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  small_test_bts:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-small_bts-${{ hashFiles('./packages/server/beaver_triple_service/**') }}
          restore-keys: ${{ runner.os }}-small_bts-

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/beaver_triple_service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=small_bts,src=/tmp/.buildx-cache
          cache-to: type=local,scope=small_bts,dest=/tmp/.buildx-cache-new
          target: small
          tags: tags_small_bts
          load: true

      - name: Run test in beaver_triple_service
        run: make test t=./beaver_triple_service m=run
        working-directory: ./scripts

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  small_test:
    runs-on: ubuntu-latest
    needs: [lint, small_test_cc, small_test_mc, small_test_bts]

    steps:
      - name: Merge All small_test
        run: echo "ok"

  medium_test_cc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/computation_container/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers cc
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-cc
          key: ${{ runner.os }}-medium_cc-${{ hashFiles('./packages/server/computation_container/**') }}
          restore-keys: ${{ runner.os }}-medium_cc-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/computation_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=medium_cc,src=/tmp/.buildx-cache-cc
          cache-to: type=local,scope=medium_cc,dest=/tmp/.buildx-cache-cc-new
          target: medium
          tags: tags_medium_cc
          load: true

      - name: Cache Docker layers bts
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-bts
          key: ${{ runner.os }}-dev_bts-${{ hashFiles('./packages/server/beaver_triple_service/**') }}
          restore-keys: ${{ runner.os }}-dev_bts-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/beaver_triple_service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=dev_bts,src=/tmp/.buildx-cache-bts
          cache-to: type=local,scope=dev_bts,dest=/tmp/.buildx-cache-bts-new
          target: dev
          tags: tags_dev_bts
          load: true

      - name: Run bazel test in computation_container
        run: make test t=./computation_container m=run p=medium
        working-directory: ./scripts

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-cc
          mv /tmp/.buildx-cache-cc-new /tmp/.buildx-cache-cc
          rm -rf /tmp/.buildx-cache-bts
          mv /tmp/.buildx-cache-bts-new /tmp/.buildx-cache-bts

  medium_test_mc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-medium_mc-${{ hashFiles('./packages/server/manage_container/**') }}
          restore-keys: ${{ runner.os }}-medium_mc-

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/manage_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=medium_mc,src=/tmp/.buildx-cache
          cache-to: type=local,scope=medium_mc,dest=/tmp/.buildx-cache-new
          target: medium
          tags: tags_medium_mc
          load: true

      - name: Run bazel test in manage_container
        run: make test t=./manage_container m=run p=medium
        working-directory: ./scripts

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  medium_test_libclient:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/computation_container/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-libc
          key: ${{ runner.os }}-medium_libc-${{ hashFiles('./packages/packages/client/libclient-py/**') }}
          restore-keys: ${{ runner.os }}-medium_libc-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./scripts/libclient/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=medium_libc,src=/tmp/.buildx-cache-libc
          cache-to: type=local,scope=medium_libc,dest=/tmp/.buildx-cache-libc-new
          target: medium
          tags: tags_medium_libc
          load: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-cc
          key: ${{ runner.os }}-dev_cc-${{ hashFiles('./packages/server/computation_container/**') }}
          restore-keys: ${{ runner.os }}-dev_cc-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/computation_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=dev_cc,src=/tmp/.buildx-cache-cc
          cache-to: type=local,scope=dev_cc,dest=/tmp/.buildx-cache-cc-new
          target: dev
          tags: tags_dev_cc
          load: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-mc
          key: ${{ runner.os }}-dev_mc-${{ hashFiles('./packages/server/manage_container/**') }}
          restore-keys: ${{ runner.os }}-dev_mc-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/manage_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=dev_mc,src=/tmp/.buildx-cache-mc
          cache-to: type=local,scope=dev_mc,dest=/tmp/.buildx-cache-mc-new
          target: dev
          tags: tags_dev_mc
          load: true

      - name: Run bazel test in libclient
        run: make test t=./libclient m=run p=medium
        working-directory: ./scripts

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-libc
          mv /tmp/.buildx-cache-libc-new /tmp/.buildx-cache-libc
          rm -rf /tmp/.buildx-cache-cc
          mv /tmp/.buildx-cache-cc-new /tmp/.buildx-cache-cc
          rm -rf /tmp/.buildx-cache-mc
          mv /tmp/.buildx-cache-mc-new /tmp/.buildx-cache-mc

  medium_test_container:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/computation_container/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pipenv
        run: pip install pipenv
        working-directory: ./scripts

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-libc
          key: ${{ runner.os }}-dev_bts-${{ hashFiles('./packages/server/beaver_triple_service/**') }}
          restore-keys: ${{ runner.os }}-dev_bts-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/beaver_triple_service/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=dev_bts,src=/tmp/.buildx-cache-bts
          cache-to: type=local,scope=dev_bts,dest=/tmp/.buildx-cache-bts-new
          target: dev
          tags: tags_dev_bts
          load: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-cc
          key: ${{ runner.os }}-dev_cc-${{ hashFiles('./packages/server/computation_container/**') }}
          restore-keys: ${{ runner.os }}-dev_cc-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/computation_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=dev_cc,src=/tmp/.buildx-cache-cc
          cache-to: type=local,scope=dev_cc,dest=/tmp/.buildx-cache-cc-new
          target: dev
          tags: tags_dev_cc
          load: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-mc
          key: ${{ runner.os }}-dev_mc-${{ hashFiles('./packages/server/manage_container/**') }}
          restore-keys: ${{ runner.os }}-dev_mc-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/server/manage_container/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,scope=dev_mc,src=/tmp/.buildx-cache-mc
          cache-to: type=local,scope=dev_mc,dest=/tmp/.buildx-cache-mc-new
          target: dev
          tags: tags_dev_mc
          load: true

      - name: Run container test
        run: make test t=./container_test m=run p=medium
        working-directory: ./scripts

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-bts
          mv /tmp/.buildx-cache-bts-new /tmp/.buildx-cache-bts
          rm -rf /tmp/.buildx-cache-cc
          mv /tmp/.buildx-cache-cc-new /tmp/.buildx-cache-cc
          rm -rf /tmp/.buildx-cache-mc
          mv /tmp/.buildx-cache-mc-new /tmp/.buildx-cache-mc

  medium_test:
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        medium_test_cc,
        medium_test_mc,
        medium_test_libclient,
        medium_test_container,
      ]

    steps:
      - name: Merge All medium_test
        run: echo "ok"
