name: Build and Run Tests on CC, MC, and BTS Containers

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format tool
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt-get update
          sudo apt-get install clang-format-14
      - name: Check if *.{cpp|hpp} files are formatted
        run: |
          cd ${{ github.workspace }}/packages/server/
          make check

  change_files:
    runs-on: ubuntu-latest
    needs: [lint]
    outputs:
      file_names: ${{ steps.output_step.outputs.file_names }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v35

      - name: Output
        id: output_step
        run: echo "file_names=${{ steps.get_changed_files.outputs.all_changed_files }}" >> "$GITHUB_OUTPUT"

  small_test_cc:
    runs-on: ubuntu-latest
    needs: [lint,change_files]
    if: contains( needs.change_files.outputs.file_names, 'computation_container')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build cc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "small_cc"
          cache-key: ${{ hashFiles('./packages/server/computation_container/**') }}
          dockerfile-path: ./packages/server/computation_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "small_tmp"

      - name: Run bazel test in computation_container
        run: make test t=./computation_container m=run p=small
        working-directory: ./scripts

  small_test_mc:
    runs-on: ubuntu-latest
    needs: [lint,change_files]
    if: contains( needs.change_files.outputs.file_names, 'manage_container')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build mc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "small_mc"
          cache-key: ${{ hashFiles('./packages/server/manage_container/**') }}
          dockerfile-path: ./packages/server/manage_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "small"

      - name: Run Go test in manage_container
        run: make test t=./manage_container m=run p=small
        working-directory: ./scripts

  small_test_bts:
    runs-on: ubuntu-latest
    needs: [lint,change_files]
    if: contains( needs.change_files.outputs.file_names, 'beaver_triple_service')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build bts with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "small_bts"
          cache-key: ${{ hashFiles('./packages/server/beaver_triple_service/**') }}
          dockerfile-path: ./packages/server/beaver_triple_service/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "small"

      - name: Run test in beaver_triple_service
        run: make test t=./beaver_triple_service m=run
        working-directory: ./scripts

  small_test:
    runs-on: ubuntu-latest
    needs: [lint, small_test_cc, small_test_mc, small_test_bts]

    steps:
      - name: Merge All small_test
        run: echo "ok"

  medium_test_cc:
    runs-on: ubuntu-latest
    needs: [lint,change_files]
    if: |
      contains( needs.change_files.outputs.file_names, 'computation_container') ||
      contains( needs.change_files.outputs.file_names, 'beaver_triple_service')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build cc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "medium_cc"
          cache-key: ${{ hashFiles('./packages/server/computation_container/**') }}
          dockerfile-path: ./packages/server/computation_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "medium"

      - name: Build bts with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "dev_bts"
          cache-key: ${{ hashFiles('./packages/server/beaver_triple_service/**') }}
          dockerfile-path: ./packages/server/beaver_triple_service/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "dev"

      - name: Run bazel test in computation_container
        run: make test t=./computation_container m=run p=medium
        working-directory: ./scripts

  medium_test_mc:
    runs-on: ubuntu-latest
    needs: [lint,change_files]
    if: contains( needs.change_files.outputs.file_names, 'manage_container')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build mc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "medium_mc"
          cache-key: ${{ hashFiles('./packages/server/manage_container/**') }}
          dockerfile-path: ./packages/server/manage_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "medium"

      - name: Run bazel test in manage_container
        run: make test t=./manage_container m=run p=medium
        working-directory: ./scripts

  medium_test_libclient:
    runs-on: ubuntu-latest
    needs: [lint,change_files]
    if: contains( needs.change_files.outputs.file_names, 'packages')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build libc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "medium_libc"
          cache-key: ${{ hashFiles('./packages/client/libclient-py/**') }}
          dockerfile-path: ./scripts/libclient/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "medium"

      - name: Build cc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "dev_cc"
          cache-key: ${{ hashFiles('./packages/server/computation_container/**') }}
          dockerfile-path: ./packages/server/computation_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "dev"

      - name: Build mc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "dev_mc"
          cache-key: ${{ hashFiles('./packages/server/manage_container/**') }}
          dockerfile-path: ./packages/server/manage_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "dev"

      - name: Run bazel test in libclient
        run: make test t=./libclient m=run p=medium
        working-directory: ./scripts

  medium_test_container_up:
    runs-on: ubuntu-latest
    needs: [lint,change_files]
    if: contains( needs.change_files.outputs.file_names, 'packages/server')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - uses: ./.github/actions/prepare_container_test

      - name: Run container test
        run: |
          pipenv sync
          pipenv install --skip-lock ../../packages/client/libclient-py
          pipenv run pytest ./tests/test_up.py -s -v -log-cli-level=DEBUG --durations=0
        working-directory: ./scripts/container_test

  medium_test_container_restart:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - uses: ./.github/actions/prepare_container_test

      - name: Run container test
        run: |
          pipenv sync
          pipenv install --skip-lock ../../packages/client/libclient-py
          pipenv run pytest ./tests/test_restart_request.py -s -v -log-cli-level=DEBUG --durations=0
        working-directory: ./scripts/container_test

  medium_test_container_down_test_failed_send_share_with_down:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - uses: ./.github/actions/prepare_container_test

      - name: Run container test
        run: |
          pipenv sync
          pipenv install --skip-lock ../../packages/client/libclient-py
          pipenv run pytest ./tests/test_down_request.py::test_failed_send_share_with_down -s -v -log-cli-level=DEBUG --durations=0
        working-directory: ./scripts/container_test

  medium_test_container_down_test_failed_execute_computation_with_down_0:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - uses: ./.github/actions/prepare_container_test

      - name: Run container test
        run: |
          pipenv sync
          pipenv install --skip-lock ../../packages/client/libclient-py
          pipenv run pytest ./tests/test_down_request.py::test_failed_execute_computation_with_down -k [down_container0] -s -v -log-cli-level=DEBUG --durations=0
        working-directory: ./scripts/container_test

  medium_test_container_down_test_failed_execute_computation_with_down_1:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - uses: ./.github/actions/prepare_container_test

      - name: Run container test
        run: |
          pipenv sync
          pipenv install --skip-lock ../../packages/client/libclient-py
          pipenv run pytest ./tests/test_down_request.py::test_failed_execute_computation_with_down -k [down_container1] -s -v -log-cli-level=DEBUG --durations=0
        working-directory: ./scripts/container_test

  medium_test_container_down_test_failed_get_computation_result_with_down:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - uses: ./.github/actions/prepare_container_test

      - name: Run container test
        run: |
          pipenv sync
          pipenv install --skip-lock ../../packages/client/libclient-py
          pipenv run pytest ./tests/test_down_request.py::test_failed_get_computation_result_with_down -s -v -log-cli-level=DEBUG --durations=0
        working-directory: ./scripts/container_test

  medium_test:
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        medium_test_cc,
        medium_test_mc,
        medium_test_libclient,
        medium_test_container_up,
        medium_test_container_restart,
        medium_test_container_down_test_failed_send_share_with_down,
        medium_test_container_down_test_failed_execute_computation_with_down_0,
        medium_test_container_down_test_failed_execute_computation_with_down_1,
        medium_test_container_down_test_failed_get_computation_result_with_down,
      ]

    steps:
      - name: Merge All medium_test
        run: echo "ok"
