name: Build CC, MC, DB and Run Build and Test in Each Containers

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format tool
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt-get update
          sudo apt-get install clang-format-14
      - name: Check if *.{cpp|hpp} files are formatted
        run: |
          cd ${{ github.workspace }}/src/
          make check

  build_test_images_cc_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}
          use_cache: true

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            dev_cc1 --push
        working-directory: ./Test

  build_test_images_cc_medium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}
          use_cache: true
          cache_name_suffix: "debug-medium"

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            medium_cc1 --push
        working-directory: ./Test

  build_test_images_cc_small:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}
          use_cache: true
          cache_name_suffix: "debug-small"

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            small_cc --push
        working-directory: ./Test

  build_test_images_mc_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            dev_mc1 --push
        working-directory: ./Test

  build_test_images_mc_medium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            medium_mc1 --push
        working-directory: ./Test

  build_test_images_mc_small:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            small_mc --push
        working-directory: ./Test

  build_test_images_db_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            dev_dbgate1 dev_sharedb1 dev_secrets-server --push
        working-directory: ./Test

  build_test_images_db_medium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            medium_dbgate --push
        working-directory: ./Test

  build_test_images_db_small:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            small_secrets-server small_sharedb small_dbgate --push
        working-directory: ./Test

  build_test_images_libc_medium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: ./.github/actions/build_test_images
        with:
          ci_package_access_token: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}
          ci_remote_cache_json: ${{ secrets.CI_REMOTE_CACHE_JSON }}
          bazel_cache_bucket: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build and Push
        run: |
          docker buildx bake -f docker-compose.yml --set *.cache-to='type=inline' \
            medium-libc --push
        working-directory: ./Test

  small_test_cc:
    runs-on: ubuntu-latest
    needs: [build_test_images_cc_small]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Enable buildkit cache
        uses: actions/cache@v3
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: ${{ runner.os }}-buildkit-${{ github.run_id }}

      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache
          cache-max-size: 4g

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./src/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./src/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build images and run ComputationContainer
        run: make test t=./ComputationContainer m=build p=small
        working-directory: ./Test

      - name: Run bazel test in ComputationContainer
        run: make test t=./ComputationContainer m=run p=small
        working-directory: ./Test

  small_test_mc:
    runs-on: ubuntu-latest
    needs: [build_test_images_mc_small]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}

      - name: Build images and run ManageContainer
        run: make test t=./ManageContainer m=build p=small
        working-directory: ./Test

      - name: Run Go test in ManageContainer
        run: make test t=./ManageContainer m=run p=small
        working-directory: ./Test

  small_test_dc:
    runs-on: ubuntu-latest
    needs: [build_test_images_db_small]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}

      - name: Build images and run secrets-server shareDbContainer DbGate
        run: make test t=./DbContainer m=build p=small
        working-directory: ./Test

      - name: Run Go test in DbContainers
        run: make test t=./DbContainer m=run p=small
        working-directory: ./Test

  small_test:
    runs-on: ubuntu-latest
    needs: [small_test_cc, small_test_mc, small_test_dc]

    steps:
      - name: Merge All small_test
        run: echo "ok"

  medium_test_cc:
    runs-on: ubuntu-latest
    needs: [build_test_images_cc_medium, build_test_images_db_dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Enable buildkit cache
        uses: actions/cache@v3
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: ${{ runner.os }}-buildkit-${{ github.run_id }}

      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache
          cache-max-size: 4g

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./src/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./src/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build images and run ComputationContainer
        run: make test t=./ComputationContainer m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in ComputationContainer
        run: make test t=./ComputationContainer m=run p=medium
        working-directory: ./Test

  medium_test_mc:
    runs-on: ubuntu-latest
    needs: [build_test_images_mc_medium, build_test_images_db_dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}

      - name: Build images and run ManageContainer
        run: make test t=./ManageContainer m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in ManageContainer
        run: make test t=./ManageContainer m=run p=medium
        working-directory: ./Test

  medium_test_dc:
    runs-on: ubuntu-latest
    needs: [build_test_images_db_medium, build_test_images_db_dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}

      - name: Build images and run DbContainer
        run: make test t=./DbContainer m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in DbContainer
        run: make test t=./DbContainer m=run p=medium
        working-directory: ./Test

  medium_test_libclient:
    runs-on: ubuntu-latest
    needs: [build_test_images_libc_medium, build_test_images_mc_dev, build_test_images_cc_dev, build_test_images_db_dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Enable buildkit cache
        uses: actions/cache@v3
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: ${{ runner.os }}-buildkit-${{ github.run_id }}

      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache
          cache-max-size: 4g

      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./src/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./src/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build images and run LibClient
        run: make test t=./LibClient m=build p=medium
        working-directory: ./Test

      - name: Run bazel test in LibClient
        run: make test t=./LibClient m=run p=medium
        working-directory: ./Test

  medium_test:
    runs-on: ubuntu-latest
    needs:
      [
        medium_test_cc,
        medium_test_mc,
        medium_test_dc,
        medium_test_libclient,
      ]

    steps:
      - name: Merge All medium_test
        run: echo "ok"
