on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  small_test_cc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build cc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "small_cc"
          cache-key: ${{ hashFiles('./packages/server/computation_container/**') }}
          dockerfile-path: ./packages/server/computation_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "small_tmp"

      - name: Run bazel test in computation_container
        run: make test t=./computation_container m=run p=small
        working-directory: ./scripts

  medium_test_cc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/computation_container/.bazelrc
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build cc with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "medium_cc"
          cache-key: ${{ hashFiles('./packages/server/computation_container/**') }}
          dockerfile-path: ./packages/server/computation_container/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "medium"

      - name: Build bts with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "dev_bts"
          cache-key: ${{ hashFiles('./packages/server/beaver_triple_service/**') }}
          dockerfile-path: ./packages/server/beaver_triple_service/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "dev"

      - name: Run bazel test in computation_container
        run: make test t=./computation_container m=run p=medium
        working-directory: ./scripts
