on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  small_test_bts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build bts with cache
        uses: ./.github/actions/build_images_with_cache
        with:
          container-name: "small_bts"
          cache-key: ${{ hashFiles('./packages/server/beaver_triple_service/**') }}
          dockerfile-path: ./packages/server/beaver_triple_service/Dockerfile
          builder-name: ${{ steps.buildx.outputs.name }}
          target: "small"

      - name: Run test in beaver_triple_service
        run: make test t=./beaver_triple_service m=run
        working-directory: ./scripts
