name: Build and Run Tests on CC, MC, and BTS Containers

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format tool
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt-get update
          sudo apt-get install clang-format-14
      - name: Check if *.{cpp|hpp} files are formatted
        run: |
          cd ${{ github.workspace }}/packages/server/
          make check

  small_test_cc:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Build images and run ComputationContainer
        run: make test t=./ComputationContainer m=build p=small
        working-directory: ./scripts

      - name: Run bazel test in ComputationContainer
        run: make test t=./ComputationContainer m=run p=small
        working-directory: ./scripts

  small_test_mc:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images and run ManageContainer
        run: make test t=./ManageContainer m=build p=small
        working-directory: ./scripts

      - name: Run Go test in ManageContainer
        run: make test t=./ManageContainer m=run p=small
        working-directory: ./scripts

  small_test_bts:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build BeaverTripleService binary
        run: make test t=./BeaverTripleService m=build
        working-directory: ./scripts

      - name: Run test in BeaverTripleService
        run: make test t=./BeaverTripleService m=run
        working-directory: ./scripts

  small_test:
    runs-on: ubuntu-latest
    needs: [lint, small_test_cc, small_test_mc, small_test_bts]

    steps:
      - name: Merge All small_test
        run: echo "ok"

  medium_test_cc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup config for using GCS as bazel remote cache
      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build images and run ComputationContainer
        run: make test t=./ComputationContainer m=build p=medium
        working-directory: ./scripts

      - name: Run bazel test in ComputationContainer
        run: make test t=./ComputationContainer m=run p=medium
        working-directory: ./scripts

  medium_test_mc:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images and run ManageContainer
        run: make test t=./ManageContainer m=build p=medium
        working-directory: ./scripts

      - name: Run bazel test in ManageContainer
        run: make test t=./ManageContainer m=run p=medium
        working-directory: ./scripts

  medium_test_libclient:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      - name: Update GCP service account JSON
        run: echo ${CI_REMOTE_CACHE_JSON} | base64 --decode >> ./packages/server/ComputationContainer/sa.json
        env:
          CI_REMOTE_CACHE_JSON: ${{ secrets.CI_REMOTE_CACHE_JSON }}

      - name: Update .bazelrc for using remote cache
        run: |
          eval "echo \"$(cat ./.github/workflows/.bazelrc_for_ci)\"" >> ./packages/server/ComputationContainer/.bazelrc
        env:
          BAZEL_CACHE_BUCKET: ${{ secrets.BAZEL_CACHE_BUCKET }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build images and run LibClient
        run: make test t=./LibClient m=build p=medium
        working-directory: ./scripts

      - name: Run bazel test in LibClient
        run: make test t=./LibClient m=run p=medium
        working-directory: ./scripts

  medium_test:
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        medium_test_cc,
        medium_test_mc,
        medium_test_libclient,
      ]

    steps:
      - name: Merge All medium_test
        run: echo "ok"
